42school/norminette

norminette/__main__.py
Bug 1: Exit code is always 1, even if all files are OK (should be 0)
Cause: `if context.errors is not []` always returns `True`, even when `context.errors` is empty
Fix: Used `if context.errors` instead
Bug 2: sentry_sdk is still used by code, thought last commit (https://github.com/42School/norminette/commit/511cd414dbae818278fd02a9e7c953e8668bfcf5) removed the `import sentry` line
Cause: `configure_scope` from sentry is still used
Fix: Commented lines still using sentry
=> Fix exit code and sentry

norminette/norm_error.py
Before:
```
vector.c: KO!
SPACE_REPLACE_TAB    (line: 19, col: 11):	Found space when expecting tab
SPACE_REPLACE_TAB    (line: 44, col: 11):	Found space when expecting tab
SPACE_EMPTY_LINE      (line: 45, col: 1):	Space on empty line
TOO_MANY_FUNCS        (line: 52, col: 1):	Too many functions in file
SPACE_REPLACE_TAB    (line: 54, col: 11):	Found space when expecting tab
SPACE_EMPTY_LINE      (line: 55, col: 1):	Space on empty line
TOO_MANY_FUNCS        (line: 92, col: 1):	Too many functions in file
SPACE_REPLACE_TAB    (line: 94, col: 111):	Found space when expecting tab
```
After:
```
vector.c: KO!
SPACE_REPLACE_TAB    (line:  19, col:  11):	Found space when expecting tab
SPACE_REPLACE_TAB    (line:  44, col:  11):	Found space when expecting tab
SPACE_EMPTY_LINE     (line:  45, col: …
```
=> Allign column and line before displaying error.

Dockerfile
Running norminette with docker on some files is not really convenient.
We should prepend `/code` for each argument.
```bash
docker run -v $PWD:/code norminette code/srcs/file.c code/includes code/file2.c
```
Can we change the working directory to `/code` ?
```bash
docker run -v $PWD:/code norminette srcs/file.c includes file2.c
```
Also, being directly in `/code` allow for autocompletion of the files.
@alexandregv  Does something relies being in the norminette's folder by default ? (like tests, or something else ?)
=> Dockerfile : Change working directory to /code

norminette/__main__.py
Fix issue #62
Wong filenames was printed from `norminette *` on files with bad extensions.
=> Fix issue "Norminette: bad work with asterisk"

.github/workflows/python-package.yml, norminette/run_test.sh
The job was able to  succeed even if a command failed in the script, example:
- `set -e` ensure to exit the script at the first command that fail.
- set -x :  to know which command failed (print each executed command)
Without :
it said it was cancelled, but it was not, I tested a timeout.
Now with `set -x` :
I have tested everything on a PR in my fork: 
https://github.com/ggjulio/norminette/pull/4#partial-pull-merging
=> Add timeout to job + fix run_tests.sh

pdf/en.norm.tex
The French word "d'affectation" should be translated as "assignment", but it was mistakenly translated as "affectation"
=> translation mistake fixed

Dockerfile
changing the line 1:
FROM python:3.7
To:
FROM python:3.7-alpine
This will shrink the size of the container from 901MB to 66.1MB
=> changing the image to python:3.7-alpine

norminette/lexer/lexer.py
it does pass all tests and fix issue #164, however there is probably a cleaner way to do this.
I made this change due to the fact we might be at the end of file without receiving the correct ch from peek_char method, assuming it wont raise empty line error.
Let me know.
=> Hard fix for #164

norminette/rules/check_preprocessor_include.py
This PR fixes a crash occurring when multiple spaces/tabs are found in an include statement.
The variable name was wrong (`tkn` instead of `tkns[i]`), leading to a crash.
Example stacktrace:
```
Traceback (most recent call last):
File "/usr/local/bin/norminette", line 11, in <module>
load_entry_point('norminette==3.3.32', 'console_scripts', 'norminette')()
File "/usr/share/norminette/venv/lib/python3.7/site-packages/norminette/main.py", line 120, in main
registry.run(context, source)
File "/usr/share/norminette/venv/lib/python3.7/site-packages/norminette/registry.py", line 63, in run
ret, jump = self.run_rules(context, rule)
File "/usr/share/norminette/venv/lib/python3.7/site-packages/norminette/registry.py", line 41, in run_rules
self.run_rules(context, self.rules[r])
File …
```
=> Fix wrong variable name in check_preprocessor_include rule

norminette/norm_error.py, norminette/rules/check_preprocessor_include.py, tests/rules/samples/ko_include2.c, tests/rules/samples/ko_include2.out
Fixed cases in which norminette would mark OK when there is no space between include and filename #383, or there is a tab between include and filename.
=> fixed norminette validating wrong includes

norminette/context.py, norminette/rules/check_preprocessor_indent.py, tests/rules/samples/check_preprocessor_indent_2.c, tests/rules/samples/check_preprocessor_indent_2.out
If we put too many `endif` or `else` without a pair, we get too many “TOO_MANY_WS” errors:
```c
#endif
#endif
#endif
#endif
#endif
#endif
```
```
Error: INVALID_HEADER       (line:   1, col:   1):      Missing or invalid 42 header
Error: PREPROC_BAD_ENDIF    (line:   1, col:   1):      Endif preprocessor statement without if, elif or else
Error: TOO_MANY_WS          (line:   1, col:   1):      Extra whitespaces for indent level
Error: TOO_MANY_WS          (line:   2, col:   1):      Extra whitespaces for indent level
Error: TOO_MANY_WS          (line:   3, col:   1):      Extra whitespaces for indent level
Error: TOO_MANY_WS          (line:   4, col:   1):      Extra whitespaces for indent level
Error: TOO_MANY_WS          (line:   5, col:   1):      Extra whitespaces for indent level …
```
=> add to PreProcessors only hold positive numbers

norminette/__main__.py
Closes https://github.com/42School/norminette/issues/416
=> Add a option --use-gitignore, for parsing only source files not match to .gitignore

pdf/pt_br.norm.tex
I did an update from PT_BR Norme version 3 to PT_BR Norme version 4
=> update pt-br norme to v4

norminette/rules/check_func_declaration.py, tests/rules/samples/ko_struct_indent.out, tests/rules/samples/ko_struct_name.out, tests/rules/samples/long_test.out
=> feat: add to check newline before braces on UserDefinedTypes

norminette/lexer/lexer.py, tests/rules/samples/test_file_2007.c, tests/rules/samples/test_file_2007.out
=> fix: add to avoid calculating the length of a escaped char in char_constant_function

norminette/norm_error.py, norminette/rules/check_utype_declaration.py, norminette/rules/is_user_defined_type.py, tests/rules/samples/check_utype_declaration_1.c, tests/rules/samples/check_utype_declaration_1.out, tests/rules/samples/check_utype_declaration_2.h, tests/rules/samples/check_utype_declaration_2.out, tests/rules/samples/ko_struct_indent.out, tests/rules/samples/ko_struct_name.out, tests/rules/samples/long_test.out, tests/rules/samples/ok_enum.out, tests/rules/samples/ok_func_name.out, tests/rules/samples/ok_func_ptr.out, tests/rules/samples/ok_struct_name.out, tests/rules/samples/ok_typedef.out, tests/rules/samples/test_comments.out, tests/rules/samples/test_file_1019.out, tests/rules/samples/test_file_1019_1.out, tests/rules/samples/test_file_1022.out, tests/rules/samples/test_file_1116_1.out, tests/rules/samples/test_file_1116_2.out, tests/rules/samples/test_file_210218_3.out, tests/rules/samples/test_file_210304.out, tests/rules/samples/testfile_210104_2.out
Fixes #437, #435 and #347.
~~I did to show an error when a struct is in a C file, but what about `enum`, `union` and `typedef`, must they also be fobidden?~~
=> Add to forbid struct in C files and in scopes that is not global

norminette/__main__.py, norminette/context.py, norminette/file.py, norminette/lexer/lexer.py, norminette/registry.py, norminette/rules/check_in_header.py, norminette/rules/check_preprocessor_protection.py, norminette/rules/check_utype_declaration.py, tests/lexer/brackets_tokens_test.py, tests/lexer/char_constant_tokens_test.py, tests/lexer/constant_tokens_test.py, tests/lexer/identifiers_tokens_test.py, tests/lexer/keywords_tokens_test.py, tests/lexer/operators_tokens_test.py, tests/lexer/string_tokens_test.py, tests/rules/rules_generator_test.py, tests/tokenizer/token_errors_test.py, tests/tokenizer/token_generator_test.py
- Add `File` class (can be used to store attributes like `source`, `tokens`, `errors`, `include`, etc.)
- Add `Errors` class (can be used in `Lexer` to avoid exceptions exiting the norminette)
- Rewrite lexer tests to `pytest` with `parametrize` fixture
- Remove old/unused code in `__main__.py`
=> add "File" and "Errors" classes

norminette/__main__.py, norminette/errors.py, norminette/file.py, norminette/registry.py, tests/rules/rules_generator_test.py, tests/test_errors.py
I'm adding a rich way of handling errors to format it as "short" (currently), "verbose" (with highlights and hints, like GCC does on errors/warnings), or others like JSON (#448).
Example of errors in JSON format:
```bash
norminette test.c --format=json
```
```json
{
"files": [
{
"path": "/home/nium/OpenSource/norminette/test.c",
"status": "Error",
"errors": [
{
"name": "INVALID_HEADER",
"text": "Missing or invalid 42 header",
"level": "Error",
"highlights": [{"lineno": 1, "column": 1, "length": null, "hint": null}]
},
{
"name": "SPACE_AFTER_KW",
"text": "Missing space after keyword",
"level": "Error",
"highlights": [{"lineno": 3, "column": 5, "length": null, "hint": null}]
}
]
}
]
}
```
Some considerations (just for now):
- `length` and `hint` is always `null`
- `highlights` always …
=> feat: add --format flag and *ErrorsFormatter classes

.github/ISSUE_TEMPLATE/bug_report.md, norminette/__init__.py, norminette/__main__.py
The version of norminette in package differs from the `pyproject.toml`. Fixed in eb78a9e9f2c5ea2fc74ab74f577003357c0efcd1.
```
$ norminette --version
norminette3.3.54, Python 3.10.12, Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
```
=> add more information in 'norminette --version' command

norminette/__main__.py, norminette/errors.py, tests/rules/rules_generator_test.py, tests/test_errors.py
This is a hotfix for #482.
If we run norminette in a folder that have more than one file, we will be surprised with an output like this:
```
a.c: OK! b.c: OK! c.c: OK!
```
Instead of:
```
a.c: OK!
b.c: OK!
c.c: OK!
```
=> fix norminette error formatters output that was not using newlines

Dockerfile, README.md
**Problem:** The Docker configuration for running norminette is not working out of the box.
- Following [PR #380](https://github.com/42School/norminette/pull/380), the minimum required version of `Python is 3.8`, but the Docker container was using `Python 3.7`.
- Dependencies are now managed by `Poetry` instead of a plain `requirements.txt` file (which has been removed, yet still referenced in the Dockerfile).
- Running the command stated in the `README` creates a new container each time, leaving unused containers behind.
**Solution:**
- Updated the Python version in the `Dockerfile` to the latest stable version (3.12).
- Updated the `Dockerfile` to use Poetry for dependency management.
- Added the `--rm` flag to the Docker run command in the `README` to automatically remove the container …
=> Fix Dockerfile python version and dependencies installation

Dockerfile
The previous PR https://github.com/42School/norminette/pull/500 changes had a problem with the Dockerfile where `poetry` couldn't be installed.
The fix was either to keep the `-alpine` version of Python, but install `gcc`, `libc-dev` and `libggi-dev` to be able to install `poetry`, or use the `-slim` that already had everything it needed.
I chose the "change the image" option, because in the end the final image was lighter (283MB vs 350MB)
=> fix(docker): Fix dockerfile poetry installation

Dockerfile
This PR fixes a Docker build issue where the `setuptools` package was missing, causing the `python3 setup.py install` step to fail.
The build process was failing at the step where `setup.py` attempts to run the installation, throwing the following error:
```
ModuleNotFoundError: No module named 'setuptools'
```
Added `setuptools` installation as part of the Docker build process to ensure that the package is available when running `python3 setup.py install`.
- Successfully built the Docker image without errors after the change.
=> Fix Docker build by explicitly installing `setuptools`

norminette/rules/is_preprocessor_statement.py, tests/rules/samples/ok_if_defined.c, tests/rules/samples/ok_if_defined.out
Fixes 42School/norminette#499
- Added 1 new test file
- Unit tests don't all pass, but modifications don't cause any additional failures
- Modifications pass flake8
The solution implemented treats defined identifier as unary operator when found within if and elif directives.
Since these directives are the only places where the word defined has a special meaning it seems unnecessary to change the dictionary or tokenizer.
The solution doesn't check if the operand is syntactically sound, but that doesn't seem necessary to assess norm adherence.
=> Handle defined operator in #if and #elif directives

norminette/rules/check_ternary.py
- Closes IN-5461
Resume of the Jira ticket :
---
We have a pisciner who submitted the code below to validate the ft_abs.h which pisciners needs to create macro from the code below. Pisciner has submitted the code below but the norminette >=3.3.51 doesn’t pass. But the next one pass.
```c
```
```c
```
It’s quite complicated as exercise if they need to think this kind of code to validate the exercises.
---
=> feat: allow ternary in define with -R CheckDefine

norminette/__main__.py
- Fixed error message when running norminette without any .c files
Please ensure the following steps have been completed:
=> fix error when no .c files are found
